config/routes.rb
EfarDispatch::Application.routes.draw do

  resource :account
  resource :session
  resources :efars do
    collection do
      get 'expired'
      get 'nyc' # not yet competent
      get 'active'
      get 'search'
      get 'bibbed'
    end
    member do
      post 'text_message'
    end
  end

  namespace :admin do
    resource :session
    resources :admins
    resources :community_centers
    resources :managers
    resources :efars do
      collection do
        get 'map'
        get 'expired'
        get 'nyc' # not yet competent
        get 'active'
        get 'search'
        get 'bibbed'
        get 'alert_subscriber'
        get 'near'
      end
      member do
        post 'text_message'
      end
    end
    resources :activity_logs
  end
  match 'admin/' => 'admin/efars#index'

  resources :text_messages
  resources :study_invites do
    member do
      get 'accept'
      get 'reject'
    end
    collection do
      get 'accepted'
      get 'pending'
    end
  end
  resources :alerts do
    collection do
      get 'efars_map'
    end
  end
  

  match 'clickatell/' => 'clickatell#callback'

  match 'admin/efars' => 'admin/efars#index', as: :admin_root
  root :to => 'efars#index'

end

app/models/community_center.rb
# == Schema Information
#
# Table name: community_centers
#
#  id                :integer          not null, primary key
#  name              :string(255)      not null
#  street            :string(255)      not null
#  suburb            :string(255)
#  postal_code       :string(255)      not null
#  city              :string(255)      not null
#  province          :string(255)
#  country           :string(255)      not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  lat               :float
#  lng               :float
#  location_type     :string(255)
#  formatted_address :string(255)
#

class CommunityCenter < ActiveRecord::Base
  attr_accessible :street, :city, :country, :name, :postal_code, :province, :suburb

  # Geocoding Attributes
  attr_accessible :lat, :lng, :location_type, :formatted_address

  validates :street, :city, :country, :name, :postal_code,
    :presence => true

  has_many :efars
  has_many :managers, dependent: :destroy
  
  geocoded_by :geocode_search_address, :latitude => :lat, :longitude => :lng do |obj, results|
    if geo = results.first
      obj.lat = geo.latitude
      obj.lng = geo.longitude
      obj.location_type = geo.types.first
      obj.formatted_address = geo.formatted_address
    end
  end 

  def geocode_search_address
    [street, suburb, city, postal_code, province, country].compact.join(", ")
  end

end

app/controllers/admin/community_centers_controller.rb
class Admin::CommunityCentersController < InheritedResources::Base
  layout 'admin'

  before_filter :require_admin_login
  respond_to :html, :json, :js

  def create
    create! { admin_community_centers_path }
  end

  def update
    update! { admin_community_centers_path }
  end

  def destroy
    @community_center = CommunityCenter.find(params[:id])
    if @community_center.efars.present?
      redirect_to admin_community_centers_path, :notice => "There are #{@community_center.efars.size} EFARs linked to this community center. You must unlink them before you can delete the community center"
    else
      destroy!
    end
  end

end

app/controllers/research/community_centers_controller.rb
class Research::CommunityCentersController < ApplicationController
  before_filter :require_researcher_login
  
  # GET /community_centers.json
  def index
    respond_to do |format|
      format.json do 
        render json: CommunityCenter.all.to_json
      end
    end
  end

end

app/views/admin/community_centers/_editor.html.haml
= form_for([:admin, @community_center], :html => {:class=> "form-horizontal"}) do |f|
  
  %legend
    Community Center
    .pull-right
      %a.btn.btn-link{:href => admin_community_centers_path } Cancel

  - if @community_center.errors.present?
    .alert.alert-error There were some errors saving the community center. See below for more information.

  = horizontal_text_field(@community_center, :name, :label => "Center Name")
  = horizontal_text_field(@community_center, :street)
  = horizontal_text_field(@community_center, :suburb)
  = horizontal_text_field(@community_center, :postal_code)
  = horizontal_text_field(@community_center, :city)
  = horizontal_text_field(@community_center, :province)
  = horizontal_text_field(@community_center, :country)

  .form-actions
    %button.btn.btn-primary{:type=>'submit'} Save

app/views/admin/community_centers/edit.html.haml
= render :partial => 'editor'

app/views/admin/community_centers/index.html.haml
= render 'shared/resource_page_header', :title => "Community Centers", :action_path => new_admin_community_center_path

%table.table
  %thead
    %tr
      %th Name
      %th Location
        

  %tbody
    - @community_centers.each do |community_center|
      %tr
        %td= community_center.name
        %td
          %small= community_center.geocode_search_address
        %td
          .btn-group
            %a.btn.btn-mini.dropdown-toggle{"data-toggle"=>"dropdown", :href=>'#'}
              %i.icon-cog
              %span.caret
            %ul.dropdown-menu.pull-right
              %li
                %a{:href=>edit_admin_community_center_path(community_center)}
                  %i.icon-pencil
                  Edit
              %li
                %a{:href=>admin_community_center_path(community_center), "data-confirm"=>"Are you sure?", "data-method"=>"delete"}
                  %i.icon-trash
                  Delete
          
.form-actions
  %a.btn.btn-primary.btn-small{:href => new_admin_community_center_path}
    %i.icon-plus.icon-white
    Add new community center  

app/views/admin/community_centers/new.html.haml
= render :partial => 'editor'